export const ACTION_TYPE = {
  SUCCESS: "SUCCESS",
  CURRENTCATEGORY: "CURRENTCATEGORY",
  SELECTEDTAB: "SELECTEDTAB",
  ADDWATCHLATER: "WATCHLATER",
  REMOVEWATCHLATER: "REMOVEWATCHLATER",
  SEARCH: "SEARCH",
  REMOVEFROMPLAYLIST: "REMOVEFROMPLAYLIST"
};
